### ISSUE TITLE
incorrect unit of entropy is wrong in doc for gsw_pt_from_entropy()?

### ISSUE THREAD

**Issue by dankelley** [TEOS-10/GSW-Matlab#8]
@PaulMBarker -- The page http://www.teos-10.org/pubs/gsw/html/gsw_pt_from_entropy.html suggests it is `degC`, but shouldn't it be `J/(kg*degC)` (or `K` for `degC`, of course).

PS. to others reading this. I am reporting findings on the webpages via issues on this repo, since I think that's more helpful than just emailing to Paul directly. (This way, others can see if I'm wrong, and--on the off chance that I may be right sometimes--they can see Paul's reply.)

D.

**Comment by durack1** [comment]
@dankelley good move, I think using the repo issue list for reporting problems is the best way forward.. Question to all watching this repo, would it be beneficial for the matlab source (including html) to be stored in github so PRs (rather than just issues) could be submitted? Many hands make light work..?

**Comment by richardsc** [comment]
> @durack1 wrote: Question to all watching this repo, would it be beneficial for the matlab source (including html) to be stored in github so PRs (rather than just issues) could be submitted? Many hands make light work..

I also agree that putting the full Matlab source into a repo would make things much easier, especially since it is currently the de-facto source for all the other translations as well as the check values. It also came up in another thread that there are other data sets that are used for checking prior to posting on the TEOS website -- I also think it would be a good idea to have those tests available for checking in the other languages.

**Comment by PaulMBarker** [comment]
All the html for the help pages is already on github. It is contained in GSW-documentation (Gibbs-SeaWater (GSW) Oceanographic Toolbox help pages in html, and associated pdf files).

The other files that I use to test GSW, I can not get large data files to upload to github.

**Comment by PaulMBarker** [comment]
Dan, I am pretty sure the units are correct as the function calculates potential temperature which is defined by Eqn. (3.1.3) in the manual.

**Comment by richardsc** [comment]
Agreed that the `pt` unit should be degC, but the help page states that the unit for **entropy** is also degC, which I think is what @dankelley was pointing out.

**Comment by PaulMBarker** [comment]
I understand now. The units for enthalpy should be J/kg

**Comment by PaulMBarker** [comment]
I understand now. yes, the units for entropy should be J/(kg*K). I will fix this.
